### ISSUE TITLE
Tracking transaction IDs

### ISSUE THREAD

**Issue by W3NDO** [W3NDO/report-block#8]
@malcolmkiano  As it stands, we're just recording different transactions. What I propose is that we have a track function, which is called by every setter method. Whenever it is called, it gets the latest accountUpdate block, and creates a new block using the old block data + the new transaction hash. 

Basically `account = [...account, newTransaction]` but blockchain. 

This way when we request all the account data, we just call the latest accountUpdateBlock.

**Comment by malcolmkiano** [comment]
I like this idea. Def will make accessing the data much easier <3

**Comment by W3NDO** [comment]
From the guys I talked to on the NEAR discord they say that the only way to get transaction IDs is from the fronted API. So I will have to design a service component on the frontend to get the txIDs, block hashes and all that data.

**Comment by W3NDO** [comment]
When you login, are you keeping track of the accountID?
